// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMf3hQnSWqp996trczg_HWxPTN5q7wviM',
    appId: '1:885826653588:web:0c504635b6ed41af065381',
    messagingSenderId: '885826653588',
    projectId: 'successapp-e73f3',
    authDomain: 'successapp-e73f3.firebaseapp.com',
    storageBucket: 'successapp-e73f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4L7gENY7sXgnNDIu62EeOgjXbm-XHyEY',
    appId: '1:885826653588:android:fd1b2be380099f5a065381',
    messagingSenderId: '885826653588',
    projectId: 'successapp-e73f3',
    storageBucket: 'successapp-e73f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC74u1Jf_MQRVFvD2OE-IBCZSvIDiHcVSE',
    appId: '1:885826653588:ios:fecc4c7203109472065381',
    messagingSenderId: '885826653588',
    projectId: 'successapp-e73f3',
    storageBucket: 'successapp-e73f3.appspot.com',
    androidClientId: '885826653588-rpr8dq9ol8hs5h4r0e6e3q085tvusc1t.apps.googleusercontent.com',
    iosClientId: '885826653588-ugp3mntjvcogli6c3886gna4prg18inl.apps.googleusercontent.com',
    iosBundleId: 'com.example.successApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC74u1Jf_MQRVFvD2OE-IBCZSvIDiHcVSE',
    appId: '1:885826653588:ios:fecc4c7203109472065381',
    messagingSenderId: '885826653588',
    projectId: 'successapp-e73f3',
    storageBucket: 'successapp-e73f3.appspot.com',
    androidClientId: '885826653588-rpr8dq9ol8hs5h4r0e6e3q085tvusc1t.apps.googleusercontent.com',
    iosClientId: '885826653588-ugp3mntjvcogli6c3886gna4prg18inl.apps.googleusercontent.com',
    iosBundleId: 'com.example.successApp',
  );
}
